# Generated by Django 4.0.1 on 2022-01-24 04:29

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='', max_length=50)),
                ('lastName', models.CharField(default='', max_length=50)),
                ('startingBalance', models.DecimalField(decimal_places=2, default='0.00', max_digits=300)),
            ],
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default='')),
                ('type', models.CharField(choices=[('withdrawal', 'withdrawal'), ('deposit', 'deposit')], default=('withdrawal', 'withdrawal'), max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=100)),
                ('description', models.TextField(blank=True, default='', max_length=300)),
                ('account', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Checkbook.account')),
            ],
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
    ]
