# Generated by Django 4.0.1 on 2022-01-24 04:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Checkbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='startingBalance',
            new_name='initial_deposit',
        ),
    ]
